HelloApp/Models/ErrorViewModel.cs
namespace HelloApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HelloApp/Models/MobileContext.cs
using Microsoft.EntityFrameworkCore;

namespace HelloApp.Models
{
    public class MobileContext : DbContext
    {
        public DbSet<Phone> Phones { get; set; }
        public DbSet<Order> Orders { get; set; }

        public MobileContext(DbContextOptions<MobileContext> options) : base(options)
        {

        }

    }
}

HelloApp/Models/Order.cs
namespace HelloApp.Models
{
    public class Order
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Adress { get; set; }
        public string? ContactPhone{ get; set; }

        public int PhoneId { get; set; }
        public Phone Phone { get; set; }

    }

    
}

HelloApp/Models/Phone.cs
namespace HelloApp.Models
{
    public class Phone
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Company { get; set; }
        public int Price { get; set; }

    }


}

HelloApp/Models/TestModel.cs
namespace HelloApp.Models
{
    public class TestModel
    {

        public string? TextMessage { get; set; }

    }


}

HelloApp/Controllers/GeometryController.cs
using Microsoft.AspNetCore.Mvc;

namespace HelloApp.Controllers;

public class GeometryController : Controller
{
    //https://localhost:7013/geometry/Square?rectangles[0].width=20&rectangles[0].height=15&rectangles[1].width=25&rectangles[1].height=80%20//%20/Geometry/Square?Width=20&Height=40

    // /Geometry/Square?
    // rectangles[0].width=20&
    // rectangles[0].height=15&
    // rectangles[1].width=25&
    // rectangles[1].height=80

    public string Square(Rectangle[] rectangles)
    {
        string temp = "";
        foreach (Rectangle item in rectangles)
        {
            temp = temp + $"Площадь прямоугольника с основанием {item.Width} и высотой {item.Height} равна {item.CalculateSquare()} \n";
        }
        return temp;
    }

    public string Square2(Rectangle rectangle)
    {
        return $"Площадь прямоугольника с основанием " +
            $"{rectangle.Width} и высотой " +
            $"{rectangle.Height} равна " +
            $"{rectangle.CalculateSquare()}";
    }


    // /Geometry/Sum?numbers=1&numbers=2&numbers=3
    public string Sum(int[] numbers)
    {
        return "Сумма чисел равна " + numbers.Sum();
    }

}
public class Rectangle
{
    public int Width { get; set; }
    public int Height { get; set; }
    public double CalculateSquare() // вычисление площади треугольника
    {
        return Width * Height;
    }
    public double CalculateSquare2() // вычисление площади треугольника
    {
        return Width + Height;
    }
}

HelloApp/Controllers/HomeController.cs
using HelloApp.Models;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Drawing;

namespace HelloApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contacts()
        {
            return View();
        }

        public IActionResult Projects()
        {
            return View();
        }

        //public IActionResult Index()
        //{
        //    return Redirect("~/Home/Privacy");
        //}
        public IActionResult Pe6e3()
        {
            return Redirect("https://pe6e3.github.io/");
        }

        public FileResult TestAction()
        {
            // Путь к файлу
            string file_path = @"~/img/Mountains/mount/1.jpg";
            // Тип файла - content-type
            string file_type = "application/octet-stream";
            // Имя файла - необязательно
            string file_name = "Gora";
            return File(file_path, file_type, file_name);
        }

        public IActionResult TestAction2()
        {
            Rectangle numbers = new Rectangle();
            numbers.Width = 13;
            numbers.Height = 11;

            //return RedirectToAction("Square2", "Geometry",numbers);
            return RedirectToAction("Square2", "Geometry", new
            {
                Width = 20,
                Height = 10
            });

        }

        public IActionResult TestRedirectToRoute()
        {
            return RedirectToRoute("default", new { controller = "Geometry", action = "Sum", numbers = 20});

        }

        public string Name(string myName, int age)
        {
            if (age < 10)
                return "Возраст слишком маленький";

            return $"текст из метода Name().\nИмя: {myName}, возраст: {age}";
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HelloApp/Controllers/PhonesController.cs
using HelloApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace HelloApp.Controllers;

public class PhonesController : Controller
{
    private MobileContext _db;
    public PhonesController(MobileContext db)
    {
        _db = db;
    }
    public IActionResult Index()
    {
        List<Phone> phones = _db.Phones.ToList();
        return View(phones);
    }

    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Add(Phone phone)
    {
        if (phone != null)
        {
            _db.Phones.Add(phone);
            _db.SaveChanges();
        }
        return RedirectToAction("Index");
    }
}

HelloApp/Controllers/SomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HelloApp.Controllers
{
    public class SomeController : Controller
    {
        [NonAction]
        public IActionResult Index()
        {
            return View();
        }

        [ActionName("Banan")] // метод Test() будет вызываться по ссылке https://localhost:7013/Some/Banan 
        public string Test()
        {
            return "Banan!";
        }
    }
}

HelloApp/Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Контакты";
}


<div class="container">
    <div class="row">
        <div class="col-2"></div>



        <div class="col-8">
            <div class="contacts">
                <h2 style="text-align:center;">Контакты</h2>
                <br>
                <div class="row-cont">
                    <p>Telegram</p>
                    <a href="https://t.me/Pe6e3"><img src="~/img/ico/telega.png" alt=""></a>
                </div>

                <div class="row-cont">
                    <p>WhatsApp</p>
                    <a href="https://wa.me/77478704750"> <img src="~/img/ico/whatsapp.png" alt=""></a>
                </div>

                <div class="row-cont">
                    <p>Instagram</p>
                    <a href="https://instagram.com/pe6e3"><img src="~/img/ico/insta.png" alt=""></a>
                </div>

                <div class="row-cont">
                    <p>Эл. почта (поправить)</p>
                    <a href="https://mailto:xpe6e3@gmail.com"><img src="~/img/ico/mail.png" alt=""></a>
                </div>

                <div class="row-cont">
                    <p>Телефон</p>
                    <a href="tel:+77478704750"> <img src="~/img/ico/mobile.png" alt=""></a>
                </div>
            </div>
        </div>

HelloApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}

<div class="container MainPage">
    <div class="row">
        <div class="col">
            <h1>Это главная страница моего сайта</h1>
            <h2>Здесь будет мое портфолио, показывающее мои навыки разработчика</h2>
            <h3>А сверху просто фотки с моих походов в горы</h3>
        </div>
    </div>
</div>

HelloApp/Views/Home/Projects.cshtml
@{
    ViewBag.Title = "Мои проекты";
    Layout = "_Layout";
}

<div class="container">
    <div class="row m-4">
        <div class="col" style="margin-bottom: 5px;">

            <div class="card">
                <img src="~/Portfolio/AnimalFarm/Feed_animal.png" class="card-img-top" alt="Feed_animal">
                <div class="card-body">
                    <h5 class="card-title text-center">Игра на юнити - Ферма животных</h5>
                    <p class="card-text ">Игра, в которой нужно кормить животных, пока они пробегают по карте</p>
                    <a href="~/Portfolio/AnimalFarm/Feed Animals.mp4" class="btn btn-danger m-2 d-flex justify-content-center">Посмотреть видео</a>
                    <a href="~/Portfolio/AnimalFarm/index3.html" class="btn btn-dark m-2 d-flex justify-content-center">Поиграть в игру</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card">
                <img src="~/Portfolio/Run-n-Jump/RunnJump.png" class="card-img-top" alt="RunNjump">

                <div class="card-body">
                    <h5 class="card-title text-center">Игра на юнити Run'n'Jump</h5>
                    <p class="card-text">Ничего особенного - с помощью клавиши Пробел нужно перепрыгивать барьеры. Попрактиковался в добавлении звуков и анимаций.</p>
                    <a href="~/Portfolio/Run-n-Jump/Run-n-Jump.mp4" class="btn btn-danger m-2 d-flex justify-content-center">Посмотреть видео</a>
                    <a href="~/Portfolio/Run-n-Jump/index2.html" class="btn btn-dark m-2 d-flex justify-content-center">Поиграть в игру</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card">
                <img src="~/img/Mountains/mount/3.jpg" class="card-img-top" alt="заглушка">

                <div class="card-body">
                    <h5 class="card-title text-center">Третий проект</h5>
                    <p class="card-text">
                        Some quick example text to build on the card title and make up the bulk of
                        the card's content.
                    </p>
                    <a href="#" class="btn btn-danger m-2 d-flex justify-content-center">Посмотреть видео</a>
                    <a href="#" class="btn btn-dark m-2 d-flex justify-content-center">Поиграть в игру</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row m-4">
        <div class="col">
            <div class="card">
                <img src="~/img/Mountains/mount/4.jpg" class="card-img-top" alt="заглушка">
                <div class="card-body">
                    <h5 class="card-title text-center">Четвертый проект</h5>
                    <p class="card-text">
                        Some quick example text to build on the card title and make up the bulk of
                        the card's content.
                    </p>
                    <a href="#" class="btn btn-danger m-2 d-flex justify-content-center">Посмотреть видео</a>
                    <a href="#" class="btn btn-dark m-2 d-flex justify-content-center">Поиграть в игру</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card">
                <img src="~/img/Mountains/mount/5.jpg" class="card-img-top" alt="заглушка">

                <div class="card-body">
                    <h5 class="card-title text-center">Пятый проект</h5>
                    <p class="card-text">
                        Some quick example text to build on the card title and make up the bulk of
                        the card's content.
                    </p>
                    <a href="#" class="btn btn-danger m-2 d-flex justify-content-center">Посмотреть видео</a>
                    <a href="#" class="btn btn-dark m-2 d-flex justify-content-center">Поиграть в игру</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card">
                <img src="~/img/Mountains/mount/6.jpg" class="card-img-top" alt="заглушка">

                <div class="card-body">
                    <h5 class="card-title text-center">Шестой проект</h5>
                    <p class="card-text">
                        Some quick example text to build on the card title and make up the bulk of
                        the card's content.
                    </p>
                    <a href="~/Portfolio/AnimalFarm/Feed Animals.mp4 Animals.mp4" class="btn btn-danger m-2 d-flex justify-content-center">Посмотреть видео</a>
                    <a href="~/Portfolio/AnimalFarm/index3.html" class="btn btn-dark m-2 d-flex justify-content-center">Поиграть в игру</a>
                </div>
            </div>
        </div>
    </div>

HelloApp/Views/Phones/Add.cshtml
@model Phone

@{
    ViewBag.Title = "Добавить устройство";
    Layout = "_Layout";
}

@*<head>
    <meta charset="UTF-8">
    <title>Login Form</title>


    <link rel="stylesheet" href="css/style.css">


</head>*@


<body-form>
    <form class='login-form' asp-action="Add" method="post">
        <div class="flex-row logo">
            <h1>Добавить устройство</h1>
        </div>

        <div class="flex-row">
            <input asp-for="Name" class='lf--input' placeholder='Модель телефона' type='text'>
        </div>

        <div class="flex-row">
            <input asp-for="Company" class='lf--input' placeholder='Производитель' type='text'>
        </div>

        <div class="flex-row">
            <input asp-for="Price" class='lf--input' placeholder='Стоимость' type='text'>
        </div>

        <input class='lf--submit' type='submit' value='Добавить'>
        <a class='lf--forgot' href='#'>Вернуться на главную</a>
    </form>
</body-form>

HelloApp/Views/Phones/Index.cshtml
@model List<Phone>

@{
    ViewBag.Title = "Мобильные телефоны";
    Layout = "_Layout";
}

<h2>Мобильные телефоны</h2>
<a asp-action="Add" asp-controller="Phones">Добавить смартфон</a>
<div class="table_section">
    @if (@Model.Count == 0)
    {
        <p>Смартфоны еще не добавлены</p>
    }
    else
    {
        <table style="width: 70%;">
            <tr>
                <th>Id</th>
                <th>Наименование</th>
                <th>Компания</th>
                <th>Стоимость</th>
            </tr>
            @foreach (var phone in @Model)
            {
                <tr>
                    <td>@phone.Id</td>
                    <td>@phone.Name</td>
                    <td>@phone.Company</td>
                    <td>@phone.Price</td>
                </tr>
            }

        </table>
    }
</div>

HelloApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelloApp</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelloApp.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/style.css" />

    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&family=Neucha&family=Raleway:ital,wght@0,400;0,800;1,400&display=swap"
          rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand navbar-style fixed-top" data-bs-theme="dark">
            <div class="container-fluid p-2">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: rgb(87, 87, 87); font-weight: bold; font-size: larger; margin-right: 50px;">АНТОН-СУПЕР-РАЗРАБОТЧИК-3000</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Phones" asp-action="Index">Телефоны</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="TestAction">Тестовый экшн</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Projects">Мои проекты</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Pe6e3">Сайт разработчика</a>
                        </li>
                </div>

            </div>
        </nav>
        <div class="top-slider">
            <div class="row ">
                <div class="container carousel">
                    <div id="slider" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="3000">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="~/img/Mountains/mount/1.jpg" alt="1">
                            </div>
                            <div class="carousel-item active">
                                <img src="~/img/Mountains/mount/2.jpg" alt="10">
                            </div>
                            <div class="carousel-item active">
                                <img src="~/img/Mountains/mount/3.jpg" alt="11">
                            </div>
                            <div class="carousel-item active">
                                <img src="~/img/Mountains/mount/4.jpg" alt="12">
                            </div>
                            <div class="carousel-item active">
                                <img src="~/img/Mountains/mount/5.jpg" alt="2">
                            </div>
                            <div class="carousel-item active">
                                <img src="~/img/Mountains/mount/6.jpg" alt="3">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>




    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>


    </div>

    <br />
    <br />
    <br />



    <footer class="border-bottom  text-muted">
    </footer>


    @*    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <script src="~/js/bootstrap.bundle.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HelloApp/Views/Some/Index.cshtml
<h2>Текст</h2>